### ISSUE TITLE
Improve checking if user is logged in

### ISSUE THREAD

**Issue by IonicaBizau** [adioo/flow-auth#2]
Right now there is only an `if (document.cookie) { /* user logged in */ }`.

Do a `getUserInfo` call to the server and then say _this user is logged in_ or not.

**Comment by IonicaBizau** [comment]
I guess this was fixed in the latest releases.

**Comment by gabipetrovay** [comment]
Nope not yet.

**Comment by gabipetrovay** [comment]
Let me take a look actually.

**Comment by IonicaBizau** [comment]
OK! :+1:

**Comment by IonicaBizau** [comment]
@gabipetrovay Is this still an issue?

**Comment by gabipetrovay** [comment]
Well I don't see it implemented. The question is if it is still needed.

**Comment by IonicaBizau** [comment]
I will just close this for now.
